SELECT COUNT(*) FROM TRANSACTION t JOIN ACCOUNT a ON t.ACCOUNT_ID = a.ID
WHERE t.CATEGORY_ID = '15' AND a.USER_ID = '356789' AND YEAR(t.POSTED_DATE) = 2013;

SELECT * FROM TRANSACTION t INNER JOIN ACCOUNT a ON t.ACCOUNT_ID = a.ID
WHERE a.USER_ID = 'user_id' AND a.NAME = 'account_name' AND MONTH(t.POSTED_DATE) = MONTH(CURRENT_DATE()) AND YEAR(t.POSTED_DATE) = YEAR(CURRENT_DATE());

--using user 356789 as example
SELECT c.NAME FROM USER u INNER JOIN ACCOUNT a ON u.ID = a.USER_ID
INNER JOIN TRANSACTION t ON a.ID = t.ACCOUNT_ID
INNER JOIN CATEGORY c ON t.CATEGORY_ID = c.ID
WHERE u.ID = '356789' AND YEAR(t.POSTED_DATE) = YEAR(CURRENT_DATE()) AND MONTH(t.POSTED_DATE) = MONTH(CURRENT_DATE()) AND t.AMOUNT > 0
GROUP BY c.ID, c.NAME;